//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yorumlar
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string İcerik { get; set; }
        public Nullable<int> Blog { get; set; }
    
        public virtual Tbl_Blog Tbl_Blog { get; set; }
    }
}
