//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Blog()
        {
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public string Resim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> Tur { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        public virtual Tbl_Tur Tbl_Tur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
